# Generated by Django 2.1.5 on 2019-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0002_auto_20190122_0553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'get_latest_by': ['-expiry_time']},
        ),
        migrations.AddField(
            model_name='job',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
