# Generated by Django 2.0.1 on 2018-09-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0002_userprofile_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar_url',
            new_name='image_url',
        ),
    ]
