# Generated by Django 2.1.5 on 2019-02-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0005_auto_20190212_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleset',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplesets', to='laxy_backend.Job'),
        ),
    ]
