# Generated by Django 2.2.4 on 2019-10-24 01:14

import collections
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0009_job_params_sampleset_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=collections.OrderedDict),
        ),
    ]
