# Generated by Django 2.2.4 on 2019-11-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0011_auto_20191029_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
