# Generated by Django 2.2.4 on 2019-10-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0012_populate_new_filelocation_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='_location',
        ),
    ]
