# Generated by Django 2.2.4 on 2019-10-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0013_remove_file__location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='secret',
        ),
    ]
