# Generated by Django 2.2.4 on 2019-11-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0014_remove_job_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeresource',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
