# Generated by Django 2.2.10 on 2020-09-02 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import laxy_backend.util


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0017_auto_20200330_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=laxy_backend.util.generate_uuid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['-modified_time'],
                'abstract': False,
            },
        ),
    ]
