# Generated by Django 2.2.10 on 2020-09-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0018_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
