# Generated by Django 2.2.10 on 2020-09-02 04:32

import collections
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0019_pipeline_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=collections.OrderedDict),
        ),
    ]
