# Generated by Django 2.2.20 on 2021-07-06 07:33

from django.db import migrations, models
import laxy_backend.util


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0021_auto_20201012_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=laxy_backend.util.generate_uuid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=256)),
                ('status', models.CharField(default='online', max_length=32)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': ['-modified_time'],
                'abstract': False,
            },
        ),
    ]
