# Generated by Django 2.2.20 on 2021-10-25 03:57

from django.db import migrations, transaction


class Migration(migrations.Migration):

    dependencies = [
        ("laxy_backend", "0024_auto_20211025_0357"),
    ]

    operations = [
        # If this fails with an error:
        # "django.db.utils.IntegrityError, 'Key (fileset_id, path, name)=(.., .., ..) is duplicated."
        # it means there are duplicate File records. You need to run the previous migration again.
        # (unfortunately it seems the previous migration and this one cannot co-exist in the same
        #  Migration transaction)
        migrations.AlterUniqueTogether(
            name="file", unique_together={("fileset", "path", "name")},
        ),
    ]
