# Generated by Django 2.2.20 on 2021-10-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laxy_backend", "0024_auto_20211025_0357"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="file", unique_together=set(),),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                condition=models.Q(fileset__isnull=False),
                fields=("fileset", "path", "name"),
                name="unique_file",
            ),
        ),
    ]
