# Generated by Django 5.2.4 on 2025-07-24 03:40

import collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0026_auto_20211025_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeresource',
            name='extra',
            field=models.JSONField(default=collections.OrderedDict),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='extra',
            field=models.JSONField(default=collections.OrderedDict),
        ),
        migrations.AlterField(
            model_name='file',
            name='metadata',
            field=models.JSONField(default=collections.OrderedDict),
        ),
        migrations.AlterField(
            model_name='job',
            name='metadata',
            field=models.JSONField(default=collections.OrderedDict),
        ),
        migrations.AlterField(
            model_name='job',
            name='params',
            field=models.JSONField(default=collections.OrderedDict),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='metadata',
            field=models.JSONField(default=collections.OrderedDict),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='params',
            field=models.JSONField(default=collections.OrderedDict),
        ),
        migrations.AlterField(
            model_name='samplecart',
            name='samples',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
