# Generated by Django 5.2.8 on 2025-11-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxy_backend', '0027_alter_computeresource_extra_alter_eventlog_extra_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filelocation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='filelocation',
            constraint=models.UniqueConstraint(fields=('url', 'file'), name='unique_filelocation_url_file'),
        ),
    ]
