// From https://github.com/ewels/AWS-iGenomes
// Generated by scripts/igenomes_list.py

import { ReferenceGenome } from "../../types";

const available_genomes: ReferenceGenome[] = [
    {
        'id': 'Homo_sapiens/Ensembl/GRCh38.release-109', 'organism': 'Homo sapiens',
        'recommended': true,
        'identifiers': { 'genbank': 'GCA_000001405.28', 'assembly_name': 'GRCh38.p13' },
        'source': 'http://Feb2023.archive.ensembl.org/Homo_sapiens/Info/Annotation',
        'files': [
            {
                'location': 'https://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz',
                'name': 'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz',
                'checksum': 'md5:239580e6119c7b16865d934f78b20a08',
                'type_tags': ['fasta'],
            },
            {
                'location': 'https://ftp.ensembl.org/pub/release-109/gtf/homo_sapiens/Homo_sapiens.GRCh38.109.gtf.gz',
                'name': 'Homo_sapiens.GRCh38.109.gtf.gz',
                'checksum': 'md5:e35a6f36d6a03d1b673659f72f1fbb3b',
                'type_tags': ['gtf', 'annotation'],
            }
        ],
        // TODO: For 'external' tagged references, frontend should treat these as 'External genomes' and
        //       grab the location from the fasta and gtf from the 'files' list, based on 'type_tag'.
        // TODO: Add 'tags': ['aws-igenomes'] to all igenomes refs
        'tags': ['external', 'rnaseq'],
    },
    { 'id': 'Homo_sapiens/Ensembl/GRCh38', 'organism': 'Homo sapiens' },
    { 'id': 'Homo_sapiens/Ensembl/GRCh37', 'organism': 'Homo sapiens' },
    { 'id': 'Homo_sapiens/NCBI/GRCh38', 'organism': 'Homo sapiens' },
    { 'id': 'Homo_sapiens/NCBI/GRCh38Decoy', 'organism': 'Homo sapiens' },
    { 'id': 'Homo_sapiens/NCBI/build37.2', 'organism': 'Homo sapiens' },
    { 'id': 'Homo_sapiens/UCSC/hg19', 'organism': 'Homo sapiens' },
    { 'id': 'Homo_sapiens/UCSC/hg38', 'organism': 'Homo sapiens' },

    {
        'id': 'Mus_musculus/Ensembl/GRCm39.release-109', 'organism': 'Mus musculus',
        'recommended': true,
        'identifiers': { 'genbank': 'GCA_000001635.9', 'assembly_name': 'GRCm39' },
        'source': 'http://Feb2023.archive.ensembl.org/Mus_musculus/Info/Annotation',
        'files': [
            {
                'location': 'https://ftp.ensembl.org/pub/release-109/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz',
                'name': 'Mus_musculus.GRCm39.dna_sm.primary_assembly.fa.gz',
                'checksum': 'md5:',
                'type_tags': ['fasta'],
            },
            {
                'location': 'https://ftp.ensembl.org/pub/release-109/gtf/mus_musculus/Mus_musculus.GRCm39.109.gtf.gz',
                'name': 'Mus_musculus.GRCm39.109.gtf.gz',
                'checksum': 'md5:',
                'type_tags': ['gtf', 'annotation'],
            }
        ],
        // TODO: For 'external' tagged references, frontend should treat these as 'External genomes' and
        //       grab the location from the fasta and gtf from the 'files' list, based on 'type_tag'.
        // TODO: Add 'tags': ['aws-igenomes'] to all igenomes refs
        'tags': ['external', 'rnaseq'],
    },
    {
        'id': 'Mus_musculus/Ensembl/GRCm38.release-102', 'organism': 'Mus musculus',
        'identifiers': { 'genbank': 'GCA_000001635.8', 'assembly_name': 'GRCm38' },
        'source': 'http://nov2020.archive.ensembl.org/Mus_musculus/Info/Annotation',
        'files': [
            {
                'location': 'https://ftp.ensembl.org/pub/release-102/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna_sm.primary_assembly.fa.gz',
                'name': 'Mus_musculus.GRCm38.dna_sm.primary_assembly.fa.gz',
                'checksum': 'md5:',
                'type_tags': ['fasta'],
            },
            {
                'location': 'https://ftp.ensembl.org/pub/release-102/gtf/mus_musculus/Mus_musculus.GRCm38.102.gtf.gz',
                'name': 'Mus_musculus.GRCm38.102.gtf.gz',
                'checksum': 'md5:',
                'type_tags': ['gtf', 'annotation'],
            }
        ],
        // TODO: For 'external' tagged references, frontend should treat these as 'External genomes' and
        //       grab the location from the fasta and gtf from the 'files' list, based on 'type_tag'.
        // TODO: Add 'tags': ['aws-igenomes'] to all igenomes refs
        'tags': ['external', 'rnaseq'],
    },
    { 'id': 'Mus_musculus/Ensembl/GRCm38', 'organism': 'Mus musculus', 'recommended': true },
    { 'id': 'Mus_musculus/NCBI/GRCm38', 'organism': 'Mus musculus' },
    { 'id': 'Mus_musculus/NCBI/build37.2', 'organism': 'Mus musculus' },
    { 'id': 'Mus_musculus/UCSC/mm10', 'organism': 'Mus musculus' },

    { 'id': 'Aedes_aegypti/VectorBase/AaegL5.2', 'organism': 'Aedes aegypti', 'recommended': true },
    { 'id': 'Aedes_aegypti/NCBI/GCF_002204515.2_AaegL5.0', 'organism': 'Aedes aegypti' },

    { 'id': 'Arabidopsis_thaliana/Ensembl/TAIR10', 'organism': 'Arabidopsis thaliana' },
    { 'id': 'Arabidopsis_thaliana/NCBI/TAIR10', 'organism': 'Arabidopsis thaliana' },
    { 'id': 'Arabidopsis_thaliana/NCBI/build9.1', 'organism': 'Arabidopsis thaliana' },

    { 'id': 'Caenorhabditis_elegans/Ensembl/WBcel235', 'organism': 'Caenorhabditis elegans' },
    { 'id': 'Caenorhabditis_elegans/Ensembl/WS220', 'organism': 'Caenorhabditis elegans' },
    { 'id': 'Caenorhabditis_elegans/NCBI/WS195', 'organism': 'Caenorhabditis elegans' },
    { 'id': 'Caenorhabditis_elegans/UCSC/ce10', 'organism': 'Caenorhabditis elegans' },

    // A turtle: https://www.ncbi.nlm.nih.gov/genome/?term=Chelonia%20mydas
    { 'id': 'Chelonia_mydas/NCBI/CheMyd_1.0', 'organism': 'Chelonia mydas' },

    { 'id': 'Danio_rerio/Ensembl/GRCz11.97-noalt', 'organism': 'Danio rerio', 'recommended': true },
    { 'id': 'Danio_rerio/Ensembl/GRCz10', 'organism': 'Danio rerio' },
    { 'id': 'Danio_rerio/NCBI/GRCz10', 'organism': 'Danio rerio' },
    { 'id': 'Danio_rerio/UCSC/danRer10', 'organism': 'Danio rerio' },

    { 'id': 'Drosophila_melanogaster/Ensembl/BDGP6', 'organism': 'Drosophila melanogaster' },
    { 'id': 'Drosophila_melanogaster/NCBI/build5.41', 'organism': 'Drosophila melanogaster' },
    { 'id': 'Drosophila_melanogaster/UCSC/dm6', 'organism': 'Drosophila melanogaster' },

    {
        'id': 'Escherichia_coli/Ensembl/GCA_000019425.1__release-46',
        'organism': 'Escherichia coli'
    },
    {
        'id': 'Escherichia_coli/Ensembl/GCA_000005845.2__release-46',
        'organism': 'Escherichia coli'
    },

    { 'id': 'Gallus_gallus/Ensembl/Galgal4', 'organism': 'Gallus gallus' },
    { 'id': 'Gallus_gallus/NCBI/build3.1', 'organism': 'Gallus gallus' },
    { 'id': 'Gallus_gallus/UCSC/galGal4', 'organism': 'Gallus gallus' },

    { 'id': 'Glycine_max/Ensembl/Gm01', 'organism': 'Glycine max' },

    { 'id': 'Oryza_sativa_japonica/Ensembl/IRGSP-1.0', 'organism': 'Oryza sativa japonica' },

    { 'id': 'Plasmodium_falciparum/PlasmoDB/3D7-release-39', 'organism': 'Plasmodium falciparum' },

    { 'id': 'Saccharomyces_cerevisiae/Ensembl/R64-1-1', 'organism': 'Saccharomyces cerevisiae', 'recommended': true },
    { 'id': 'Saccharomyces_cerevisiae/NCBI/build3.1', 'organism': 'Saccharomyces cerevisiae' },

    { 'id': 'Sus_scrofa/Ensembl/Sscrofa10.2', 'organism': 'Sus scrofa' },
    { 'id': 'Sus_scrofa/NCBI/Sscrofa10.2', 'organism': 'Sus scrofa' },
    { 'id': 'Sus_scrofa/UCSC/susScr3', 'organism': 'Sus scrofa' },

    { 'id': 'Zea_mays/Ensembl/AGPv3', 'organism': 'Zea mays' },
];

export default available_genomes;
