version: '3.2'
services:

  db:
    ports:
      # postgres accessible on the host at 5433 for debugging
      - "5433:5432"

  django:
    build: .
    environment:
      # - LAXY_DEBUG=yes
      - LAXY_ADMIN_EMAIL=admin@example.com
      - LAXY_ADMIN_USERNAME=admin
      - LAXY_ADMIN_PASSWORD=adminpass
    volumes:
      - .:/app
    # Django app is publicly accessible without reverse proxy
    ports:
      - "8001:8001"
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "1"
    command: bash -c "sleep 10 &&
                      python3 manage.py collectstatic --no-input &&
                      python3 manage.py makemigrations --no-input &&
                      python3 manage.py migrate --no-input &&
                      python3 manage.py runserver 0.0.0.0:8001 &&
                      python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='${LAXY_ADMIN_USERNAME}').count() or User.objects.create_superuser('${LAXY_ADMIN_USERNAME}', '${LAXY_ADMIN_EMAIL}', '${LAXY_ADMIN_PASSWORD}');\";"

  celeryd:
    command: bash -c "celery -A laxy worker -B -E -l debug --broker=${LAXY_BROKER_URL}"
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "1"

  flower:
    environment:
      - FLOWER_BASIC_AUTH=user:pass
    ports:
      - "5556:5556"
    volumes:
      - .:/app

  nginx:
    ports:
       # dev
       - "8002:80"
    volumes:
      - ./laxy_frontend/dist:/usr/share/nginx/html:ro
