version: '3.2'
services:

  django:
    build: .
    environment:
      - LAXY_DEBUG=yes
      - LAXY_ADMIN_EMAIL=admin@example.com
      - LAXY_ADMIN_USERNAME=admin
      - LAXY_ADMIN_PASSWORD=adminpass
    volumes:
      - .:/app
    # Django app is publicly accessible without reverse proxy
    ports:
      - "8001:8001"
    command: bash -c "python3 manage.py makemigrations &&
                      python3 manage.py migrate &&
                      python3 manage.py runserver 0.0.0.0:8001 &&
                      python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.filter(username='${LAXY_ADMIN_USERNAME}').count() or User.objects.create_superuser('${LAXY_ADMIN_USERNAME}', '${LAXY_ADMIN_EMAIL}', '${LAXY_ADMIN_PASSWORD}');\";"

  celeryd:
    volumes:
      - .:/app

  flower:
    environment:
      - FLOWER_BASIC_AUTH=user:pass
    ports:
      - "5556:5556"
    volumes:
      - .:/app

  nginx:
    ports:
       # dev
       - "8002:80"
    volumes:
      - ./laxy_frontend:/usr/share/nginx/html
