version: "3.7"

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - test-dbdata:/var/lib/postgresql/data/pgdata
    networks:
      - test-net
    # ports:
    #   # postgres accessible on the host at 5433 for debugging
    #   - "5433:5432"

  sut:
    image: laxy:dev
    build:
      context: .
      dockerfile: ./docker/laxy/Dockerfile
    environment:
      - LAXY_DEBUG=yes
      - LAXY_SSL=no
      - LAXY_DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - LAXY_BROKER_URL=amqp://guest@rabbitmq
      - LAXY_ADMIN_EMAIL=admin@example.com
      - LAXY_ADMIN_USERNAME=admin
      - LAXY_ADMIN_PASSWORD=adminpass
      - LAXY_SECRET_KEY=_do_please_change_this_in_production_
      - LAXY_USE_SSL=no
      # For pytest
      - DJANGO_SETTINGS_MODULE=laxy.settings
    # volumes:
    #   - .:/app
    # Django app is publicly accessible without reverse proxy
    # ports:
    #   - "8001:8001"
    networks:
      - test-net
    depends_on:
      - db
    # command: python3 ./manage.py test
    command: bash -c "pip install -U -r requirements-dev.txt && pytest"

  test-dev:
    image: laxy:test
    build:
      context: .
      dockerfile: ./docker/laxy-test/Dockerfile
    environment:
      - LAXY_DEBUG=yes
      - LAXY_SSL=no
      - LAXY_DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - LAXY_BROKER_URL=amqp://guest@rabbitmq
      - LAXY_ADMIN_EMAIL=admin@example.com
      - LAXY_ADMIN_USERNAME=admin
      - LAXY_ADMIN_PASSWORD=adminpass
      - LAXY_SECRET_KEY=_do_please_change_this_in_production_
      - LAXY_USE_SSL=no
      # For pytest
      - DJANGO_SETTINGS_MODULE=laxy.settings
    volumes:
      - .:/app
    ports:
      #  Debugger port
      - "21001:21001"
    networks:
      - test-net
    depends_on:
      - db
    # command: python3 ./manage.py test
    command: pytest
    # command: pytest laxy_backend/tests/test_util.py

  ##
  # Disabled services not required for simple local dev, overridden from base docker-compose.yml
  ##

  # For simple local development, we run in Django debug mode (LAXY_DEBUG=yes) with CELERY_ALWAYS_EAGER=True
  # so that celery tasks run non-async in the Django process. We don't need the celery daemon in this case.
  queue-high:
    image: alpine
    entrypoint:
      - /bin/echo
    command: "Service disabled"
    restart: "no"

  queue-low:
    image: alpine
    entrypoint:
      - /bin/echo
    command: "Service disabled"
    restart: "no"

  celery-beat:
    image: alpine
    entrypoint:
      - /bin/echo
    command: "Service disabled"
    restart: "no"

  # We don't need flower if we aren't using celeryd
  flower:
    image: alpine
    entrypoint:
      - /bin/echo
    command: "Service disabled"
    restart: "no"

  nginx:
    image: alpine
    entrypoint:
      - /bin/echo
    command: "Service disabled"
    restart: "no"
    ports:
      # dev
      - "9999:80"

  portainer:
    image: alpine
    entrypoint:
      - /bin/echo
    command: "Service disabled"
    restart: "no"

volumes:
  test-dbdata:

networks:
  test-net:
