---
# A simpler conda env without explicit dependencies.
name: rnasik-1.5.3-laxydev
channels:
  # Custom channel just for laxytest versions of the pipeline
  - pansapiens
  - conda-forge
  - bioconda
  - serine
  - serine/label/dev
  - anaconda
  - defaults
  - r
  # conda-forge occasionally re-labels packages from 'main' to 'broken',
  # so we need this to make the environment reproducible
  - conda-forge/label/broken
dependencies:
  # General run_job.sh dependencies. Many of these will already exist on a typical
  # Linux system but we pull them in explicitly to ensure they are available, even on
  # barebones systems (eg slimmed down Docker containers)
  - python
  - pip
  - aria2
  - curl
  - wget
  - awscli
  - jq
  - parallel
  # Pipeline specific
  - rnasik=1.5.3.laxydev
  - mash
  - pip:
    # General run_job.sh dependency, for the laxydl downloader tool
    - git+https://github.com/MonashBioinformaticsPlatform/laxy@master#egg=laxy_downloader&subdirectory=laxy_downloader
