// From https://github.com/ewels/AWS-iGenomes
// Generated by scripts/igenomes_list.py

// nf-core/rnaseq available iGenomes codes are (Dec-2022):
//   GRCh37, GRCh38, GRCm38, TAIR10, EB2, UMD3.1, WBcel235, CanFam3.1, GRCz10, BDGP6, EquCab2, EB1, 
//   Galgal4, Gm01, Mmul_1, IRGSP-1.0, CHIMP2.1.4, Rnor_5.0, Rnor_6.0, R64-1-1, EF2, Sbi1, Sscrofa10.2, 
//   AGPv3, hg38, hg19, mm10, bosTau8, ce10, canFam3, danRer10, dm6, equCab2, galGal4, panTro4, rn6, 
//   sacCer3, susScr3

import { ReferenceGenome } from "../../../../types";

const available_genomes: ReferenceGenome[] = [
    { 'id': 'Homo_sapiens/NCBI/GRCh38', 'organism': 'Homo sapiens', 'recommended': true },
    { 'id': 'Homo_sapiens/NCBI/GRCh38Decoy', 'organism': 'Homo sapiens' },
    { 'id': 'Homo_sapiens/NCBI/build37.2', 'organism': 'Homo sapiens' },

    // iGenomes does not have Ensembl/GRCh38 (Dec-2022) - defaults to the NCBI ref+annotation
    // { 'id': 'Homo_sapiens/Ensembl/GRCh38', 'organism': 'Homo sapiens', 'recommended': true },
    { 'id': 'Homo_sapiens/Ensembl/GRCh37', 'organism': 'Homo sapiens' },

    { 'id': 'Homo_sapiens/UCSC/hg19', 'organism': 'Homo sapiens' },
    { 'id': 'Homo_sapiens/UCSC/hg38', 'organism': 'Homo sapiens' },

    { 'id': 'Mus_musculus/Ensembl/GRCm38', 'organism': 'Mus musculus', 'recommended': true },
    { 'id': 'Mus_musculus/NCBI/GRCm38', 'organism': 'Mus musculus' },
    { 'id': 'Mus_musculus/NCBI/build37.2', 'organism': 'Mus musculus' },
    { 'id': 'Mus_musculus/UCSC/mm10', 'organism': 'Mus musculus' },

    { 'id': 'Arabidopsis_thaliana/Ensembl/TAIR10', 'organism': 'Arabidopsis thaliana' },
    { 'id': 'Arabidopsis_thaliana/NCBI/TAIR10', 'organism': 'Arabidopsis thaliana' },
    { 'id': 'Arabidopsis_thaliana/NCBI/build9.1', 'organism': 'Arabidopsis thaliana' },

    { 'id': 'Caenorhabditis_elegans/Ensembl/WBcel235', 'organism': 'Caenorhabditis elegans' },
    { 'id': 'Caenorhabditis_elegans/Ensembl/WS220', 'organism': 'Caenorhabditis elegans' },
    { 'id': 'Caenorhabditis_elegans/NCBI/WS195', 'organism': 'Caenorhabditis elegans' },
    { 'id': 'Caenorhabditis_elegans/UCSC/ce10', 'organism': 'Caenorhabditis elegans' },

    { 'id': 'Danio_rerio/Ensembl/GRCz11.97', 'organism': 'Danio rerio', 'recommended': true },
    { 'id': 'Danio_rerio/Ensembl/GRCz10', 'organism': 'Danio rerio' },
    { 'id': 'Danio_rerio/NCBI/GRCz10', 'organism': 'Danio rerio' },
    { 'id': 'Danio_rerio/UCSC/danRer10', 'organism': 'Danio rerio' },

    { 'id': 'Drosophila_melanogaster/Ensembl/BDGP6', 'organism': 'Drosophila melanogaster' },
    { 'id': 'Drosophila_melanogaster/NCBI/build5.41', 'organism': 'Drosophila melanogaster' },
    { 'id': 'Drosophila_melanogaster/UCSC/dm6', 'organism': 'Drosophila melanogaster' },

    { 'id': 'Gallus_gallus/Ensembl/Galgal4', 'organism': 'Gallus gallus' },
    { 'id': 'Gallus_gallus/NCBI/build3.1', 'organism': 'Gallus gallus' },
    { 'id': 'Gallus_gallus/UCSC/galGal4', 'organism': 'Gallus gallus' },

    { 'id': 'Glycine_max/Ensembl/Gm01', 'organism': 'Glycine max' },

    { 'id': 'Oryza_sativa_japonica/Ensembl/IRGSP-1.0', 'organism': 'Oryza sativa japonica' },

    { 'id': 'Plasmodium_falciparum/PlasmoDB/3D7-release-39', 'organism': 'Plasmodium falciparum' },

    { 'id': 'Saccharomyces_cerevisiae/Ensembl/R64-1-1', 'organism': 'Saccharomyces cerevisiae', 'recommended': true },
    { 'id': 'Saccharomyces_cerevisiae/NCBI/build3.1', 'organism': 'Saccharomyces cerevisiae' },

    { 'id': 'Sus_scrofa/Ensembl/Sscrofa10.2', 'organism': 'Sus scrofa' },
    { 'id': 'Sus_scrofa/NCBI/Sscrofa10.2', 'organism': 'Sus scrofa' },
    { 'id': 'Sus_scrofa/UCSC/susScr3', 'organism': 'Sus scrofa' },

    { 'id': 'Zea_mays/Ensembl/AGPv3', 'organism': 'Zea mays' },
];

export default available_genomes;
