<template>
                    <md-boards :md-controls="true" :md-swipeable="true">
                        <md-board id="slide1">
                            <vue-markdown>
                                <!-- @formatter:off -->
Provide a URL to a page where your data can be downloaded. This could be a web page containing links to your files, or a URL to a `.tar` format file.
Valid protocols are `http://`, `https://` or `ftp://`.
<!-- @formatter:on -->
                            </vue-markdown>
                        </md-board>
                        <md-board id="slide2">
                            <vue-markdown>
                                <!-- @formatter:off -->
**Examples:**

`https://bioinformatics.erc.monash.edu/home/andrewperry/test/sample_data/`
will list the files found on the page (eg a default Apache directory index page).

`https://bioinformatics.erc.monash.edu/home/andrewperry/test/sample_tar_data/data.tar`
will list the files *inside* the TAR file, if there is a corresponding
`data.tar.manifest-md5` file generated by `md5sum` on the TAR file contents.

If there is no corresponding `.manifest-md5` file, the TAR file can be added directly -
it will be untarred by the pipeline and the entire contents used as input.
<!-- @formatter:on -->
                            </vue-markdown>
                        </md-board>
                    </md-boards>
</template>

<script lang="ts">
    import Vue from "vue";
    import Component from "vue-class-component";
    import VueMarkdown from 'vue-markdown';

    @Component({
        components: {'vue-markdown': VueMarkdown},
        filters: {}
    })
    export default class RemoteFileSelectAboutBox extends Vue {}
</script>
